# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61d49d62f0e3bb69b0c71d98deaf0288bdcdb32aadcda2f32e567284f8deb113fcb8c365c0243ae06655c9867613f6fab1c86434a1aaf3f642f657349e99847f

test:
  secret_key_base: ebcca014ea338fac5864ca5304b44b59dc2cfc6b50b60b1aff37d85cd78a22cddf5301fc0179a207bb1088ed2df10ae9543b6d98440b7af05295cd99527dd9c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
